version: '3'
services:
  gps:
    image: gps
    container_name: gps
    ports:
      - "8889:8889"
    networks:
      - default

  rewards:
    image: rewards
    container_name: rewards
    ports:
      - "8787:8787"
    networks:
      - default

  tripdeals:
    image: tripdeals
    container_name: tripdeals
    ports:
      - "8888:8888"
    networks:
      - default

  tourguidev2:
    depends_on:
      - gps
      - tripdeals
    image: tourguide
    container_name: tourguide
    ports:
      - "8080:8080"
    networks:
      - default

    